Feature/screen layout 1
1knowledge1/MTS.Teta-Project pull request #1
Opened 2021-07-13 10:04 UTC by 1knowledge1

2021-07-14 08:42 UTC, NikolayUkhvarov requested changes

2021-07-14 08:42 UTC, NikolayUkhvarov commented on app/src/main/res/drawable/ic_home.xml
> +    android:viewportHeight="21">
лучше сделать четные размеры и более одинаковые

2021-07-14 08:42 UTC, NikolayUkhvarov commented on app/src/main/res/layout/bottom_sheet_movie_details.xml
> +            android:paddingVertical="1dp"
откуда 1?

2021-07-14 12:25 UTC, 1knowledge1 commented on app/src/main/res/drawable/ic_home.xml
> +    android:viewportHeight="21">
Можно исправить только width и height? Изменить viewportHeight корректно не получается, т.к. точки в path используют значения до 21.

2021-07-16 08:29 UTC, NikolayUkhvarov approved these changes

2021-07-16 09:01 UTC, merged